### ISSUE TITLE
Possible Duplicates - ldd Cards

### ISSUE THREAD

**Issue by hcallen** [jonasjacek/lpic-1-anki-flashcards#2]
Card fronts:
Command to find out the locations of shared libraries needed by a program?
Command to check out which shared objects (libraries) a program needs?

"Command to find out the locations of shared libraries needed by a program?" more thoroughly purveys the same information as "Command to check out which shared objects (libraries) a program needs?".

**Comment by jonasjacek** [comment]
Deleted duplicate card. Will be released with the next update.
Thank you for your time and help! It is highly appreciated.
