### ISSUE TITLE
Erroneous Answer - Display LD_LIBRARY_PATH Contents 

### ISSUE THREAD

**Issue by hcallen** [jonasjacek/lpic-1-anki-flashcards#4]
Card Front: Command to display the contents of environment variable LD_LIBRARY_PATH?
Card Back: $ print $LD_LIBRARY_PATH

I believe an appropriate answer would be "echo $LD_LIBRARY_PATH".

**Comment by jonasjacek** [comment]
Obviously. 
Again, thank you for taking the time to point out the error.
Fix will be released with the next update.
